#!/bin/sh
#Create device nodes


mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev


export PATH=$PATH:/usr/local/sbin/
export PATH=$PATH:/sbin
export PATH=$PATH:/usr/sbin/

exec /bin/bash
